### ISSUE TITLE
Error detected while processing function / Invalid sign text on save

### ISSUE THREAD

**Issue by joshpasqualetto** [mhinz/vim-signify#105]
Hi, 

On saving/updating of a file I get the following error, the file saves anyway but this is showing up after the save. If I remove vim-signify from my plugins list (I am using spf13) it stops happening, however, this is the coolest plugin in the whole lot so -- I do not want go without it :)

Error detected while processing function sy#start..sy#highlight#line_disable:
line   15:
E239: Invalid sign text: <bf>

**Comment by halostatue** [comment]
Just an FYI, I am seeing this error as well trying to use Kana’s vim-emoji to specify signs for signify (it took me a long time to realize that this conflicts with quickfixsigns_vim) and I am getting this error on setting most of these to emoji. I believe that the issue is that signs must be exactly one or two cells wide and emoji (and some of these other characters) are two cells wide themselves. So when you want to display 🔺 1 or 💥 1, that doesn’t work because it is now three cells wide.

This is probably a documentation issue that should be clarified, or vim-signify should consider checking the character width (I believe that `strwidth` will do the job correctly) before adding numbers to a wide display character.

**Comment by mhinz** [comment]
@halostatue Confirmed. Currently it only handles single-cell characters correctly. I'll look into it.

**Comment by mhinz** [comment]
@jamessan What do you think about this approach:

```diff
diff --git i/autoload/sy/sign.vim w/autoload/sy/sign.vim
index c4b1031..76619ef 100644
--- i/autoload/sy/sign.vim
+++ w/autoload/sy/sign.vim
@@ -99,5 +99,4 @@ function! sy#sign#process_diff(sy, vcs, diff) abort
-        if old_count <= 99
-          let text = substitute(s:sign_delete . old_count, '.*\ze..$', '', '')
-        else
-          let text = s:sign_delete .'>'
-        endif
+        let text = s:sign_delete . (old_count <= 99 ? old_count : '>')
+        while strwidth(text) > 2
+          let text = strcharpart(text, 1)
+        endwhile
```

**Comment by halostatue** [comment]
The only thing that I’d say is that I have some code protecting against `strwidth` because it was also relatively new at one point. :)

**Comment by mhinz** [comment]
I'm a fan of [https://github.com/tweekmonster/helpful.vim](helpful.vim), which gives me info about when a feature was introduced when I hover over a tag in the help:

![helpful.vim](https://i.imgur.com/AN87qFZ.png)

+7.3 is good enough for me. :-)

@halostatue It would be nice, if you could test https://github.com/mhinz/vim-signify/pull/242.
