### ISSUE TITLE
stage and revert hunks

### ISSUE THREAD

**Issue by acornejo** [mhinz/vim-signify#119]
This is a feature from gitgutter which I miss.

Staging individual modified hunks for commiting later, and reverting the staging of individual hunks.

**Comment by j201** [comment]
In gitgutter, the 'revert' feature [doesn't unstage staged changes](https://github.com/airblade/vim-gitgutter/blob/master/README.mkd#getting-started); it just changes the hunk in the file to whatever the last committed/staged version of the hunk was.  As such, I don't think it's a VCS-specific feature.

Given that, could the 'revert' feature be looked at again? It's definitely something I miss from gitgutter.

**Comment by mhinz** [comment]
I welcome proof-of-concepts, but I doubt that undoing hunks is easy (especially for all supported VCS) given [gitgutter's implementation](https://github.com/airblade/vim-gitgutter/blob/master/autoload/gitgutter.vim#L204-L224).

Which VCS do you use? Can you roughly describe how it would work with your VCS?

**Comment by j201** [comment]
It seems to me that this could be done just with the diff for each hunk. For example, if I have this hunk:

```
a
b
c
1
2
3
```

And the diff with the previous version is

```diff
 a
 b
 c
-d
-e
-f
+1
+2
+3
```

Then calling the revert command with my cursor on line 4 would get the diff for the hunk, and replace the added lines with the removed lines to get

```
a
b
c
d
e
f
```

Since signify has access to diff files and matches them to line numbers, it seems to me that it could perform this kind of substitution without VCS-specific code.

The `git apply` command there seems to me more or less equivalent to `patch --reverse`. It's not using any repo information or making any changes to the repo, it's just git's particular implementation of patching. Since the patch is limited to one hunk, I don't think this would be too difficult to add on to signify's existing diff handling, although I don't know enough about the code to be sure.

**Comment by mhinz** [comment]
Sy only knows the starting/end line number and the type of the hunk. Since we compare against an actual file.

Let's add 2 lines:

```diff
diff --git i/autoload/sy/repo.vim w/autoload/sy/repo.vim
index ce36349..0421e99 100644
--- i/autoload/sy/repo.vim
+++ w/autoload/sy/repo.vim
@@ -146,0 +147,2 @@ function! s:expand_cmd(cmd, path) abort
+  let cmd = s:replace(cmd,   '%d', s:difftool)
+  let cmd = s:replace(cmd,   '%d', s:difftool)
```

Then Sy knows this about hunks:

```
 'hunks': [{ 'start': 147, 'end': 148, 'ids': [259, 262] }],
```

When trying to revert the hunk, we could filter the diff output from all lines that apply to lines 147 and 148. We didn't even need to use `patch` in that case. Am I missing something?

@jamessan Opinion?

**Comment by jamessan** [comment]
That assumes the user isn't working with a modified buffer, which I doubt is a safe assumption to make.  If the buffer is modified, the hunk information we have stored may not actually line up with the current contents of the buffer.  That means, at best, we don't revert the hunk (because it doesn't line up anymore) or, at worst, revert some other hunk that happens to fall into that range now.

**Comment by acornejo** [comment]
Diffing and applying patches is a strategy that has worked for git fairly well.

If you modified the file and the diff doesnt applies/reverts cleanly then you simply notify the user you cant apply/revert due to a conflict.

In the case where it does apply cleanly then for the majority of cases all is good, and in the cases where it isn't the user can hit undo.

**Comment by BonarBeavis** [comment]
@acornejo you can do this with [vim-fugitive](https://github.com/tpope/vim-fugitive).
See [here], (http://vimcasts.org/episodes/fugitive-vim-working-with-the-git-index/) paragraph "Piecemeal reconciliation" explains it with some nice pictures.

**Comment by EduardoRT** [comment]
@BonarBeavis Thanks! It's been some time since I've wanted to use signify instead off gitgutter, but the quickly hunk stage/undo are something I use several times a day.

I do have fugitive installed but I didn't know about the :diffput and :diffget vim commands, that's gonna solve most of my problem, still it's gonna be a more cumbersome to open the diff instead of just staging it/ undoing it quickly but it's a good workaround.

– Thanks!

**Comment by kevincox** [comment]
It seems like there was interest in the "revert" feature. Should we open a new issue to track that independently? It apparents like this was closed due to being VCS specific however the "revert" part of the request isn't VCS specific. The other noted concern was version skew between the diff and the live buffer, however I heard rumors that diffing against non-saved buffers is in the works which should resolve that issue. Shall I file something to track the "revert" command so that it will be remembered after that is implemented?

**Comment by TamaMcGlinn** [comment]
Now that it's implemented, you can revert a hunk with `:SignifyHunkUndo`
