### ISSUE TITLE
vim-signify is very slow on large files.

### ISSUE THREAD

**Issue by haifengkao** [mhinz/vim-signify#190]
### Steps to Reproduce 

1. download the 10MB json file https://raw.githubusercontent.com/Fngi/taipower_MAPS/gh-pages/result.json
2. open it with vim
3. vim won't show anything due the slowness of vim-signify
4. press `ctrl-c` to stop the vim-signify scripts
5. the screen will show up

![2016-10-04 5 43 19](https://cloud.githubusercontent.com/assets/4080524/19069697/84fb8f46-8a5a-11e6-95e4-50815dace353.jpg)

### related 
https://github.com/rhysd/NyaoVim/issues/89#event-811470586

**Comment by mhinz** [comment]
I can't reproduce it with neither Vim nor Neovim. I tried opening the downloaded file and the file as part of the repo. No difference. I experience a short delay, but Vim isn't that good at handling big files and disabling Sy makes no difference.

What is your environment? OS? What signify options have you set?

**Comment by haifengkao** [comment]
This issue happens when the file is added as a new file.  I suppose that it means every line of the file has been changed? Is it the expected behavior?

**Comment by mhinz** [comment]
> Is it the expected behavior?

Yes, unfortunately.

Adding a new file to the repo means creating a diff where every line counts newly added.

Making sense of the diff itself is the bottleneck for this kind of plugin, because a [lot of logic](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/sign.vim#L56-L194) has to be applied. It's long a function, but everything is needed and I wouldn't know how to optimize it any further.

Maybe we create an option that simply skips further steps after a certain threshold? Maybe..

```vim
let g:signify_sign_threshold = 1000
```

...would stop processing the diff after 1000 signs and flash a warning message? Should we keep these 1000 or disable the plugin for that file?

What do you think, @jamessan?

**Comment by jamessan** [comment]
I think two things. :)

1. This is a pathological case which only occurs when `git add -N file` has happened with a very large file or a very large file is deleted.
2. Vim's performance for sign manipulation is awful.  It's another case of quadratic performance that should be sub-linear (like [tag lookup]).

So, my take would be "don't do that" for 1. and I'll fix 2. if no one beats me to it.

[tag lookup]: https://github.com/vim/vim/pull/1046

**Comment by mhinz** [comment]
I agree with (1) and would love to see (2). :-)

@haifengkao Is that a solution you can live with?

**Comment by haifengkao** [comment]
(1) is good enough for me :)

**Comment by mhinz** [comment]
Great, this can be closed then. Thanks for raising this issue!
