### ISSUE TITLE
autocmd User Fugitive SignifyRefresh makes cursor jump with vimtex

### ISSUE THREAD

**Issue by languitar** [mhinz/vim-signify#193]
When using vimtex and setting `autocmd User Fugitive SignifyRefresh`, the cursor moves to other windows in case the internal callback for presenting the errors is called.

In order to reproduce this (neovim, recent master):
1. Configure signify and vimtex
1. `:vsplit`, move cursor back to the left window
1. Open a tex file in a git project
1. `:call vimtex#latexmk#callback(1)`

The cursor jumps to the right window. This doesn't happen if the autocmd is not set.

**Comment by languitar** [comment]
When looking at the implementation of `refresh_windows`, I suspect there is some kind of race condition with the quickfix window appearing in between and therefore changing the window count. But that's just a guess.

**Comment by mhinz** [comment]
Could you test if the above commit fixes your problem?

Do this in the repo:

```
$ git fetch origin pull/194/head && git checkout FETCH_HEAD
```

**Comment by languitar** [comment]
No, doesn't help

**Comment by mhinz** [comment]
Is it vimtex or fugtive opening the quickfix window?

**Comment by languitar** [comment]
vimtex. Especially, because I call a vimtex function in step 4. However, the cursor also jumps in case the window is already open.

**Comment by mhinz** [comment]
> because I call a vimtex function in step 4

But that callback probably does `doau Fugitive` somehow or not? Otherwise I wouldn't see how the autocmd you mentioned would be important.

The cursor probably jumps to the last window of the tabpage, because of `:windo`. But at least in my local tests the use of `win_gotoid()` (from the PR) takes me back to the window where `:SignifyRefresh` was executed from.

`:window` itself isn't amused about a changing window layout during execution, but as you said yourself, it also happens with the quickfix window already opened.

**Comment by languitar** [comment]
>> because I call a vimtex function in step 4
> But that callback probably does doau Fugitive somehow or not? Otherwise I wouldn't see how the autocmd you mentioned would be important.

vimtex doesn't interact with fugitive up to my knowledge.

**Comment by mhinz** [comment]
I'm confused. When is `SignifyRefresh` used at all then?

According to your first post it's executed on the user event "Fugitive", but fugitive gets never called?

**Comment by languitar** [comment]
Oh, maybe I should have added that fugitive plugin is also enabled. But I have no idea how this happens and who calls this. I just see the result and the effect is definitely gone with the autocommand.

**Comment by mhinz** [comment]
You can just run `:SignifyRefresh` with a few windows opened and see if it always returns to the correct window.

If `:SignifyRefresh` returns to a wrong window in your use case, it's most probably because any of the autocmds before it changed to that window and there's nothing I can do about that from this plugin.

You could try this:

```vim
autocmd User Fugitive echomsg "Win ID before SignifyRefresh:" win_getid() | SignifyRefresh
echomsg "Win ID before callback:" win_getid() | call vimtex#latexmk#callback(1)
```

The IDs should be equal, but my guess is they aren't.

**Comment by languitar** [comment]
You are right. This is what happens:
```
Win ID before callback: 1001                                                                                                                                                                                                                   
Win ID before SignifyRefresh: 1002
```

**Comment by languitar** [comment]
I see something like this in the fugitive source code:
```
  autocmd CmdWinEnter * call fugitive#detect(expand('#:p'))
  autocmd BufWinLeave * execute getwinvar(+bufwinnr(+expand('<abuf>')), 'fugitive_leave')
```
I suspect that at least on of them is called when the quickfix window appears or gets updated. Maybe this in turn results in a user event.

Is there any way to get stacktraces in vim?

**Comment by mhinz** [comment]
I'm closing this as it's no issue in Sy, but let's try to find a solution to your problem anyway.

Unfortunately I have no working LaTeX environment on this Mac, so I can't really test it with vimtex.

What happens if you use the commands from above again with an already opened quickfix window?

```vim
autocmd User Fugitive echomsg "Win ID before SignifyRefresh:" win_getid() | SignifyRefresh
echomsg "Win ID before callback:" win_getid() | call vimtex#latexmk#callback(1)
```

If the IDs are equal, then we can assume it's because of vimtex, not fugitive.

**Comment by languitar** [comment]
This gives:
```
Win ID before callback: 1001                                                                                                                                                                                                                   
Win ID before SignifyRefresh: 1003
```

**Comment by languitar** [comment]
I looked a bit through the vimtex code. The code that potentially opens the quickfix window uses `wincmd p` to return to the previous window and the signify refresh function is called before that is executed. Could it be that something that `refresh_windows` does, prevents `wincmd p` from returning to the correct window?

**Comment by languitar** [comment]
I could get around the issue by patching vimtex as explained in lervag/vimtex#637
