### ISSUE TITLE
Intro screen flashes when launching vim

### ISSUE THREAD

**Issue by winsphinx** [mhinz/vim-signify#229]
I test in window 7 and 10, two PCs both appear this result.
And before the commit `at d155dff GUI: use :redraw for all GUIs except MacVim`, -> no splash screen.
And after `at 01bcf8a Win/gVim: fix "no signs at start" race`, -> it appears.

And I just commited line 48:
`    autocmd GUIEnter * redraw`
no splash screen shown.

**Comment by mhinz** [comment]
I can't reproduce it with gVim 8.x on Windows 10. Actually, as the code comment says, I need that `GUIEnter` event, because otherwise it _could_ be that signs aren't written at startup.

1. I take it you use gVim. Is the version older than 7.4.1967?
1. What wonders me the most, is that vim-startify and vim-signify shouldn't run _both_ at start. Startify doesn't run if arguments were given, e.g. it runs only on `gvim` without any files given. But when started that way, Sy will the skip the first buffer since it's not a readable file on disk. So, how do you start gvim exactly?
1. Try `gvim -V1` and check `:messages` afterwards. It prints what Sy is doing exactly.

**Comment by winsphinx** [comment]
Thanks for your answers, and:
1. My vim is vim 8.363, [download from](https://bintray.com/micbou/generic/vim), and my vimrc is [here](https://github.com/winsphinx/MyDesktop/blob/master/.vimrc)
2. No g:signify_realtime  set, default is 0
3. I just click a shortcut of gvim.exe, without anything else - no files, no arguments.
4. With -V1, no messages abort Sy; and when open a file, some messages are below:
![snap](https://cloud.githubusercontent.com/assets/5674054/23331599/3e91732a-fba4-11e6-9d8e-ae9831d55549.png)

**Comment by mhinz** [comment]
> But i'd renamed Signity into zzz for I had thought zzz would launch after Starify, but it still appears.

Well, that might sources `vim-signify` (or `zzz`) after `vim-startify`, but the former acts on `GUIEnter` and the latter on `VimEnter`. The help for `GUIEnter` states that it gets executed _before_ `VimEnter`, so the main code for vim-signify runs before vim-startify anyway.

For my gVim on Win 10 I need the `autocmd GUIEnter * redraw` workaround, because sometimes signs aren't shown at startup. (They get placed, but gVim hasn't redrawn the screen yet. That's why I force a screen redraw on `GUIEnter`.) It has nothing to do with having a filename given or not.

So, vim-signify runs and runs a few async processes to detect the used version control system (this is the delay you see), during that time, the intro could be shown, then it goes away because vim-startify starts creating its menu.

**Comment by mhinz** [comment]
> But i'd renamed Signity into zzz for I had thought zzz would launch after Starify, but it still appears.

Well, that might sources `vim-signify` (or `zzz`) after `vim-startify`, but the former acts on `GUIEnter` and the latter on `VimEnter`. The help for `GUIEnter` states that it gets executed _before_ `VimEnter`, so the main code for vim-signify runs before vim-startify anyway.

For my gVim on Win 10 I need the `autocmd GUIEnter * redraw` workaround, because sometimes signs aren't shown at startup. (They get placed, but gVim hasn't redrawn the screen yet. That's why I force a screen redraw on `GUIEnter`.) It has nothing to do with having a filename given or not.

So, vim-signify runs and runs a few async processes to detect the used version control system (this is the delay you see), during that time, the intro could be shown, then it goes away because vim-startify starts creating its menu.

**Comment by mhinz** [comment]
Startify now disables the intro on its own if `g:startify_disable_at_vimenter` isn't set.

Hopefully I understand: This issue is just about the flashing, right? There's no delay because of that autocmd, right?

**Comment by winsphinx** [comment]
Yes, it seems to work as before. Thank you very much.
Now i'm confused that in this case vim-startify or vim-signity, which one is the cause while which is the return? Luckily they both are your great work.

**Comment by winsphinx** [comment]
Usually gvim is run in two ways -- `gvim` or `gvim filename`, I guess that the autocmd `GUIEnter` in signity is used to shown the changes in filename for the latter case. So if just run gvim merely, the autocmd is unnecessary.
IMHO, can it be solved by testing if a filename provided to run this `au`? (I don't know if VimL has method to test filename.)

**Comment by mhinz** [comment]
Good idea.

I used `argc()`, which returns the number of files in the argument list (`:h arglist`). So, if it's 0 during startup, no files were given.

**Comment by winsphinx** [comment]
Okay, It works perfectly.
Thanks for your great work.

**Comment by mhinz** [comment]
Thanks for bringing this up!
