### ISSUE TITLE
Save in MacVim 

### ISSUE THREAD

**Issue by borissov** [mhinz/vim-signify#234]
Save in MacVim in insert mode return code "^L" . When stop the plugin is OK. MacVim version 8.0.525 . How can I fix this?

**Comment by mhinz** [comment]
I can't reproduce it with MacVim 8.0.130 (brew) and MacVim 8.0.562 (brew --HEAD).

Create a file `/tmp/vimrc`:

```vim
set rtp+=~/.vim/bundle/vim-signify  " change path according to your environment
set nocompatible
```

Now start MacVim in your repo like this:

```
$ mvim -u /tmp/vimrc file_from_repo
```

When you save now, do you still see the `^L`?

**Comment by borissov** [comment]
I try to make a gif. Uploaded here: https://s7.postimg.org/cglzgepbf/out.gif

**Comment by mhinz** [comment]
From all the GUIs, MacVim is a special case as it's the only GUI that needs a manual screen refresh for signs getting updated immediately. I hope that gets fixed in the future.

`<c-l>` (which produces the `^L` in insert mode) refreshes the screen in normal mode.

The latest commit makes MacVim only issue the `^L` in normal mode. This means when you write in insert mode, it might happen that the signs don't get updated immediately, even after `'updatetime'` milliseconds. In normal mode signs get updated as expected.

This should be good enough for the meantime.

Does it work for you?

**Comment by borissov** [comment]
Thanks!
