### ISSUE TITLE
Syntastic errors block updating of signify

### ISSUE THREAD

**Issue by rezadril** [mhinz/vim-signify#237]
For some reason I need to double save to update signify signs if a change induces an error which syntastic shows.

**Comment by jamessan** [comment]
Vim can only show one sign per line.  You have two plugins competing for that sign -- signify and syntastic.  Since syntastic is loaded after signify (due to alphabetic ordering), syntastic's autocommands run after signify's and overwrite the signs.

There's not really anything Sy can do about that.  Besides, the current behavior (by chance) actually seems preferred since errors should have higher precedence than marking changed lines.

**Comment by jamessan** [comment]
> syntastic's autocommands run after signify's and overwrite the signs.

Actually, Sy explicitly defers to signs placed by other plugins since https://github.com/mhinz/vim-signify/commit/fe3bafce1180881f5d2a4ffa9b7e9c0d5c853fc4.

**Comment by rezadril** [comment]
Yeah, it makes sense about the signs being occupied by two different plugins.

The weird part is that i see that sy#repo#get_stats gets updated only after the second save. Should the write autocommands clash for those two plugins too?

**Comment by jamessan** [comment]
With new enough (n)vim, Sy runs the commands asynchronously, so I suspect it's not that you need to save again but that it's a little lagged due to competing for resources with whatever syntastic is running.  If you just save once and then wait, the stats should get updated.

**Comment by rezadril** [comment]
Indeed they get updated when i refresh with Ctrl-L.

**Comment by mhinz** [comment]
The manual screen refresh shouldn't be needed. Usually.

Do you use a GUI by any chance? Maybe MacVim?

**Comment by rezadril** [comment]
No, I'm using gnome-terminal. Any movement triggers a refresh (or just manually refreshing), but waiting will not trigger the refresh from my experiments.

**Comment by jamessan** [comment]
> Any movement triggers a refresh (or just manually refreshing), but waiting will not trigger the refresh from my experiments.

Yeah, I wasn't clear enough there.  I just meant that waiting will let Sy finish but vim tries to avoid unnecessary redraws.  Doing pretty much anything will cause it to redraw, at which point the signs will become visible.

**Comment by mhinz** [comment]
Okay, so I tried the following in gnome-terminal in a Ubuntu 17.04 VM:

```
$ cat >/tmp/vimrc <<EOF
set rtp+=~/.vim/bundle/vim-signify
set rtp+=~/.vim/bundle/syntastic

set nocompatible
syntax on
EOF
$ vim -u /tmp/vimrc version-controlled-file.rb
```

Everything works as expected for me. Adding a line and doing `:w` will show the added line in Sy (and therefore `sy#repo#get_stats()`) instantly. I don't have move or do anything to let the screen refresh.

I also paid attention to disable the blinking cursor because that refreshes the screen as well.

Changing a character which breaks the syntax leads to exact one sign (check with `:sign place`) from syntactic.

In `:au BufWritePost` one can see that Sy runs _before_ syntastic, but it runs async tasks. Before these tasks end, syntastic runs as well (and blocks everything, so Sy can't do anything now). When syntastic finshed, the exit handlers for Sy's tasks run and see that another plugin already set a sign at one certain line and won't bother overwriting it.

It's a bit odd that you see a different behaviour (having to do something to let the screen refresh). Hmm.

**Comment by jamessan** [comment]
Does it make a difference if you switch the order of the `set rtp` lines?

**Comment by mhinz** [comment]
I assume one changed line:

1. syntastic
1. vim-signify

Here syntastic runs first and Sy doesn't bother overwriting the signs from syntastic. `:sign place` only shows one sign for the line.

1. vim-signify
1. syntastic

Sy runs first and actually sets the sign before syntastic. But syntastic will bluntly write over it. `:sign place` shows 2 signs for the line. The ID doesn't matter. The last set sign (from syntastic) wins.
