### ISSUE TITLE
Invalid diff command for darcs

### ISSUE THREAD

**Issue by dolio** [mhinz/vim-signify#243]
Hello,

I keep most of my personal stuff in darcs repos, and I've been trying out signify with them. Unfortunately, the diff command you have for darcs doesn't work (anymore). The problem is that darcs doesn't recognize the escaped `'diff'` as an executable in the custom `--diff-command` specified.

The easiest way I found to fix the issue is to not try to use `--diff-command` at all. Instead, pass the flags `--no-unified --diff-opts=-U0` to the `darcs diff` command. This tells darcs not to pass the `-u` flag to the diff command, which was overriding the `-U0` flag. It also moves darcs out of the category of tools that rely on the custom diff tool machinery, of course.

I can probably put together a patch if desired.

**Comment by mhinz** [comment]
Hmm.

[When darcs support was added over 4 years ago](https://github.com/mhinz/vim-signify/commit/8cf6c61), darcs didn't support unified diffs.

The actual problem is that our template:

```
darcs diff --no-pause-for-gui --diff-command="%d -U0 %1 %2" -- %f
```

gets replaced by the _already escaped_ `diff` tool by default:

```
darcs diff --no-pause-for-gui --diff-command="'diff' -U0 %1 %2" -- '/tmp/repo/foo'
```

Removing the single quotes around `diff` makes it work again.

Anyway, if darcs support unified context on its own now, yes, we should probably ditch `--diff-command`. 

If darcs uses `--diff-opts=-U0`, I assume that it uses the external diff command itself internally. So, why is `darcs diff --diff-opts=-U0` not working? Shouldn't this just translate to `diff -U0` internally? Why would `--unified` or `--no-unified` make any difference? Is it a bug? (And people say git's UX is terrible!)

**Comment by dolio** [comment]
The first line of the output gives the command that was run. With `--unified` (the default) and `--diff-opts=-U0`, it's:

`diff -rN -u -U0 %1 %2`

And `diff` appears to ignore `-U0` when `-u` is given.

I'll put together a patch.

**Comment by mhinz** [comment]
I see. So I guess that `darcs diff --no-unified` simply leaves away the `-u` when using `diff` in return.

That means that `darcs diff --diff-opts=-U0` only doesn't work as expected, because `darcs` defaults to unified output whereas `diff` does not. Otherwise it would simply translate to `diff -rN -U0 %1 %2`.

Thanks for looking into it!

**Comment by mhinz** [comment]
@dolio 

Since it's a rather grave issue (for all darcs users), I just committed the change myself now.

Thanks for bringing up this issue!

**Comment by dolio** [comment]
Okay. Sorry about the delay. I got a bit distracted. Thanks for fixing it.
