### ISSUE TITLE
Different diff with -U0

### ISSUE THREAD

**Issue by michaelmior** [mhinz/vim-signify#245]
This seems to be a git bug, but I wonder if there's a workaround that could be implemented. git produces a different diff in some cases with `-U0`. For example, without `-U0` I get a diff like

```
+ foo {
+   bar
+ }
```

With `-U0`, this becomes

```
+   bar
+ }
+ foo {
```

This is because `bar }` is repeated in the block above the newly added section. I think the second diff is clearly more desirable. I wonder if we could just use `-U1` and then trim the extra lines of context.

**Comment by mhinz** [comment]
Yup, the less context git has, the higher the chance that it chooses the "wrong" place in repeating texts like your case. It's actually correct, just not what you would expect.

Anyway, the [algorithm](https://github.com/mhinz/vim-signify/blob/1a8a15d835d8f2da56cd793a0222227af6c89839/autoload/sy/sign.vim#L53-L205) which processes the diff output expects no context at all, and that way works for all supported tools the same.

It would be interesting to know if one of the other diff algorithms would make any difference, but I think not, because of the lacking context. Search for `--diff-algorithm` in `git help diff`. If so, you could overwrite the default `git diff` command used by the plugin by using `:h g:signify_vcs_cmds`.

Since this is no bug in this plugin (or git), I'm closing this. But if you happen to find a `--diff-algorithm` that works, I'll gladly add it to the plugin.

Thanks!

**Comment by michaelmior** [comment]
I've tried all the diff algorithms unfortunately and none of them produce better output. I didn't think that the the context argument affected in any way what git sees while generating the diff. I assumed this was just the number of lines of context that were included when the diff was generated.

**Comment by mhinz** [comment]
In this case we should just accept that status quo. On the plus side, this really only happens in those cases with repeating text which shouldn't be all too often.

Nevertheless, thanks for bringing this up!
