### ISSUE TITLE
[c and ]c hops seem to only find the signs, not the true changes

### ISSUE THREAD

**Issue by unphased** [mhinz/vim-signify#247]
I use signify to get a git diff gutter, and it's great. I also use the `[c` and `]c` for hunk jumping.

However, if I have a single line hunk, and it happens to have an ALE warning on it (which in effect overrides the signify sign, which is preferred, errors/warnings take precedence over git info), the hunk jumping skips it over!

I realize that this has got to be just a side effect of the implementation, which uses signs. But the assumption that each hunk has got signs associated with it seems... overly optimistic?

**Comment by mhinz** [comment]
Here is the thing:

1. Hunk jumping only works when a sign got _placed_ on a line.
1. The last placed sign on a line always wins. The others are still there, but the sign column (often incorrectly called "gutter") will show the text from the last set one.

> if I have a single line hunk, and it happens to have an ALE warning on it (which in effect overrides the signify sign, which is preferred, errors/warnings take precedence over git info)

Sy won't place signs on lines that have signs already. That is done for the exact reason you mentioned, but comes with the tradeoff that Sy can't jump to that line anymore, because without a sign, you can't jump.

Now, it would be easy to introduce a new option that changes this behaviour, but then you wouldn't see the Ale signs anymore.

So.. when I have to choose between no working hunk jumping in some cases and _not_ overwriting other signs, I choose the latter.

Unfortunately Vim simply offers no better way to solve this problem. Sorry!

**Comment by unphased** [comment]
Thanks! I was definitely suspecting that this was likely to be a built in limitation that would be impossible to work around, I appreciate you confirming that and explaining!
