### ISSUE TITLE
RCS support seems broken

### ISSUE THREAD

**Issue by fourjay** [mhinz/vim-signify#251]
I've made several attempts with signify, which seems ideal to me, but I've never managed to get RCS support working (I still use it for some ad-hoc work).

I've just made another attempt. SignifyDebug seems to show that signify recognizes the change, but the signs do not show :-(

    rcsdiff -U0 '/home/fortier/tmp/src/rcs/test/test.txt' 2>/dev/null
    =================================================================
    --- /home/fortier/tmp/src/rcs/test/test.txt     2018/02/20 19:53:16     1.1
    +++ /home/fortier/tmp/src/rcs/test/test.txt     2018/02/20 19:53:40
    @@ -1,0 +2,2 @@
    + 
    +This is a second

What additional troubleshooting should I do?

**Comment by fourjay** [comment]
``SignifyList`` does appear sane.

``:sign place`` shows no output (or more accurately a ``--- Signs ---`` banner with no content

``:au BufWritePost`` shows about 10 different plugis tied to the the even. No obvious to my issues.

Similar test with CVS and ``SignifyList`` and ``sign place`` show output

I'm paring down a test .vimrc.

**Comment by fourjay** [comment]
Pared down to a single plugin, signify, with no better results.

Possibly the output of ``SignifyList`` isn't so sane

   /home/joefort/tmp/src/vim/signify/test.txt
  ==========================================
    active  =  1
    buffer  =  1
       vcs  =  []
     stats  =  -1 added, -1 changed, -1 removed
    signid  =  256
     hunks  =  []

**Comment by mhinz** [comment]
Hmm!

The stats all get initialized with -1, so either the [plugin is disabled by `g:signify_disable_by_default = 1`](https://github.com/mhinz/vim-signify/blob/e8cb5b636c48979607ee25ec0ba883d83c7092be/autoload/sy.vim#L44-L48)  or `sy#set_signs()` was never called, because [it would set all stats to 0](https://github.com/mhinz/vim-signify/blob/e8cb5b636c48979607ee25ec0ba883d83c7092be/autoload/sy.vim#L88-L90).

Please do this:

```
$ vim -V1 file_with_changes
```

You'll get some verbose output that you can click away with any key. Then paste the output of `:messages` here. (Everything below `[sy] Register new file.` is enough.)

**Comment by mhinz** [comment]
Actually, I can reproduce it locally now. Let me look into it.

**Comment by mhinz** [comment]
Apparently the return values of `rcsdiff` changed since RCS support was added. Now it returns 1 if there are _some_ changes, but Sy thought of everything other than 0 as an error and returned no diff.

Should be fixed now. Thanks for bringing this up! ✨
