### ISSUE TITLE
vim-ale integration

### ISSUE THREAD

**Issue by towc** [mhinz/vim-signify#265]
I'm using vim-ale to display linting errors, and it also uses the sign column. I love the idea of this plugin, but I love linting more :/

Can something be done about this?

**Comment by jamessan** [comment]
Sy specifically [avoids placing signs](https://github.com/mhinz/vim-signify/blob/a9fc705b9bdffaac46f13e47d6565c904102dedc/autoload/sy/sign.vim#L260-L269) where another plugin has placed a sign, so this should Just Work.

**Comment by towc** [comment]
it doesn't overwrite it, but after I update something that removes the linting error, the sign columns are just empty for me, until I update something else :/

**Comment by jamessan** [comment]
That's an issue with Vim.  You can't have multiple signs in the same place, which is why Sy will avoid placing a sign if one from another plugin exists.  If the other plugin's sign is removed, nothing will show up from Sy until it is triggered again.  There's nothing we can do about that since there's no way for Sy to know that the other sign was removed.
