### ISSUE TITLE
Handling multiple VCS

### ISSUE THREAD

**Issue by mathomp4** [mhinz/vim-signify#274]
All, 

I currently happen to work at times in a codebase that is both a CVS and git repository. Yes, this Should Not Be™, but we are trying to move this code from CVS to git and this is allowing us to slowly migrate code from CVS to git in a smoother way than just moving straight to git.

My question is I currently have:

`let g:signify_vcs_list = [ 'cvs', 'git' ]`

and when I open a file with vim, the CVS changes are the ones being signify'd. If I change the order above, CVS is still displayed. My question is: is there a way to say "make git the priority if more than one VCS is found"?

**Comment by mhinz** [comment]
Argh. ;-)

First and foremost, please open one of those files with `vim -V1 <file>`. Then `:w`. And then paste the output of `:messages` beginning at `[sy] Register new file`.

I want to make sure that both VCS are detected as expected.

Honestly, I'm not sure how the above will work out, because so far we only added support for multiple VCS when there were _nested_, like a hg repo below a git repo etc.

**Comment by mathomp4** [comment]
Here you go. This system I logged onto has `['git','cvs','svn']`. Time to sync up my .vimrc's.

```
[sy] Register new file: /gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_GITDEV/CURRENT/JU/src/GMAO_Shared/MAPL_Base/CFIOCollection.F90
[sy:git] get_diff_start()
[sy:git] CMD: ['sh', '-c', 'git diff --no-color --no-ext-diff -U0 -- ''CFIOCollection.F90'''] | CWD: /gpfsm/dnb02/mathomp4/SystemTests/bui
lds/AGCM_GITDEV/CURRENT/JU/src/GMAO_Shared/MAPL_Base
[sy:cvs] get_diff_start()
[sy:cvs] CMD: ['sh', '-c', 'cvs diff -U0 -- ''CFIOCollection.F90'''] | CWD: /gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_GITDEV/CURRENT/J
U/src/GMAO_Shared/MAPL_Base
[sy:svn] get_diff_start()
[sy:svn] CMD: ['sh', '-c', 'svn diff --diff-cmd ''diff'' -x -U0 -- ''/gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_GITDEV/CURRENT/JU/src/G
MAO_Shared/MAPL_Base/CFIOCollection.F90'''] | CWD: /gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_GITDEV/CURRENT/JU/src/GMAO_Shared/MAPL_Ba
se
[sy:git] job_exit()
[sy:git] get_diff_git()
[sy:git] get_diff_end()
[sy:git] set_signs()
[sy:git] No changes found.
[sy:svn] job_exit()
[sy:svn] get_diff_svn()
[sy:svn] get_diff_end()
[sy:svn] No valid diff found. Disabling this VCS.
[sy:cvs] job_exit()
[sy:cvs] get_diff_cvs()
[sy:cvs] get_diff_end()
[sy:cvs] set_signs()
[sy:cvs] Signs updated.
[sy:cvs] Disable all other VCS.
"CFIOCollection.F90" 149L, 4221C written
[sy:cvs] Updating signs.
[sy:cvs] get_diff_start()
[sy:cvs] CMD: ['sh', '-c', 'cvs diff -U0 -- ''CFIOCollection.F90'''] | CWD: /gpfsm/dnb02/mathomp4/SystemTests/builds/AGCM_GITDEV/CURRENT/J
U/src/GMAO_Shared/MAPL_Base
[sy:cvs] job_exit()
[sy:cvs] get_diff_cvs()
[sy:cvs] get_diff_end()
[sy:cvs] set_signs()
[sy:cvs] Signs updated.
```

**Comment by mhinz** [comment]
Here's how Sy works (using your output as example):

- It checks if `g:signify_vcs_list` is set. Here it is, so it will only care about git, cvs, and svn.
- Sy shells out once for each of the three VCS. VimL itself is single-threaded, but the "shelling out part", which takes the longest by far (I/O bound) compared to the rest of the plugin's code, is done asynchronously. All 3 commands start almost at the same time. So, they get started in the order of `['git', 'cvs', 'svn']`, but return in the order of `['git', 'svn', 'cvs']`, which is normal from my experience.
- The `svn diff` command exits with an invalid value, so there are not only no svn changes, but no svn repo at all, so Sy disables svn for all subsequent checks.
- Only `['git', 'cvs']` left. Both, `git diff` and `cvs diff`, exit with valid values. So they're considered for further processing.
- Here lies your problem. There's no good way to handle multiple VCS changes at the same time, so Sy checks git and cvs until one of them returns a _non-empty_ diff. And in your case that's cvs, so git gets disabled as well for all subsequent checks. (If both VCS would return with a non-empty diff, the last one would always win.)

(You can always use `:SignifyList` to see which buffers are managed by Sy and which VCS were detected.)

So, right now, the best you can do is to simply remove cvs from `g:signify_vcs_list` . One could come up with an autocmd that does so only for that particular project.

It's surely possible to come up with a solution that prefers the VCS coming first in `g:signify_vcs_list` in case there are multiple VCS returning valid diffs, but it would quite some code to do the right thing, because of the asynchronous nature of the plugin.

And even then some people might have different needs for different projects. For this project Sy should prefer git, and for that project cvs. Let's say it: it's a mess. :-)

Maybe there's a more straight-forward solution: Offering a way to force a certain VCS. E.g. `:SignifyForce git`. Doing that only for the current buffer should be very easy to implement. Doing that for all currently managed buffers _and_ future buffers backed by files from the current working directory and below would take quite a bit more code.

The more user-friendly the solution, the more code it takes and the less I'm sure if it's all worth it, considering the use case of having multiple VCS per project almost never happens (and for a good reason ;-))

@jamessan What's your opinion? :)

**Comment by jamessan** [comment]
I agree that the cost-benefit probably isn't worthwhile here to add robust support for multiple VCS managing a single directory.

**Comment by mhinz** [comment]
Okay, then it's decided.

@mathomp4 

The idea is declined because the case is uncommon enough that it doesn't warrant the time for all this new code (and potental bugs).

Thanks for bringing it to our attention anyways! ✨
