### ISSUE TITLE
Preview hunks

### ISSUE THREAD

**Issue by GreenCourt** [mhinz/vim-signify#300]
Thanks for developing this cool plugin!
Signify helps my daily works a lot.

This is a feature request.
I want to look hunks in a preview window (or a popup window).

As shown in the following screenshot, vim-gitgutter has this feature.
![Screen Shot 2019-07-16 at 21 45 33](https://user-images.githubusercontent.com/45067835/61297309-f1252100-a816-11e9-88e9-23f2b76a65c6.png)

Although I know the function `SignifyDiff`, I want to see the changes more casually.

**Comment by mhinz** [comment]
Okey-dokey! Please update the plugin and try out `:SignifyPreviewHunk`.

Notes:

- Not yet documented.
- Naming: Currently it's `:SignifyPreviewHunk`, but I'm not sure if it's a great name. `:SignifyPreview` would be shorter and `:SignifyDiffPreviewHunk` would be more exact (and goes well together with the already existing `:SignifyDiff`). Opinions?
- Opposed to vim-gitgutter the preview window is not resized for small diffs on purpose. It's about expectability. When I open a new window, I know how my current window gets resized. I know exactly where my eyes needs to wander. That's not the case if I'd resize the window though.

**Comment by t0str** [comment]
I just wanted to say I really like the idea of the feature. Stumbled on it by chance in the commit log today. Personally I found these mappings to work amazingly well from a workflow perspective:

```
nmap ]c <plug>(signify-next-hunk):SignifyPreviewHunk<CR>
nmap [c <plug>(signify-prev-hunk):SignifyPreviewHunk<CR>
```

I only jump along humps if I care about the changes anyway, so this makes it like reading the commit to index history of a file. But other maps that don't use ]/[c could also be used obv.

Thanks for the great work!

**Comment by GreenCourt** [comment]
Thanks for your work!
I updated to the revision https://github.com/mhinz/vim-signify/commit/736466ccce6aaac5e2bd08b3157af1d2e42656a4 and tried it.
This is what I wanted.

I found that ...

* When the whole line is deleted, sometimes hunks are not shown. I am not sure about the condition to reproduce.

And just my **_personal_** opinions,

- I prefer `:SignifyDiffPreview`,  because I can find it at the next of `:SignifyDiff` by tab-completion and it is shorter than `:SignifyDiffPreviewHunk`.
- I think the key-mapping suggested by t0str https://github.com/mhinz/vim-signify/issues/300#issuecomment-520404403 is very useful, although some users feel it annoying.  To include the mappings, `]C` and `[C` (upper case) instead?
- Currently, the popup window hides the buffer texts  (I tried on Vim). Can it be shown at above or below the lines signed by this plugin?

**Comment by mhinz** [comment]
> When the whole line is deleted, sometimes hunks are not shown. I am not sure about the condition to reproduce.

You mean the sign isn't shown or that the preview isn't working? If there's no preview even though there is a sign, it's definitely a bug.

> I prefer `:SignifyDiffPreview`, because I can find it at the next of `:SignifyDiff` by tab-completion and it is shorter than `:SignifyDiffPreviewHunk`.

I think the length doesn't really matter, since most people will map it anyway, but yes, I prefer `:SignifyDiffPreview` as well. Will change that.

> I think the key-mapping suggested by t0str #300 (comment) is very useful, although some users feel it annoying. To include the mappings, `]C` and `[C` (upper case) instead?

The upper case variants are already used in signify for jumping to the first/last hunk. Since it's not a feature on its own, I will probably just add these mappings are suggestions to `:h signify-example`.

> Currently, the popup window hides the buffer texts (I tried on Vim). Can it be shown at above or below the lines signed by this plugin?

Yeah, I thought the same. I'm also tempted to make the popup window use the whole width of the window starting from col 1 (no matter where the cursor is in the line). That way we will have more space for the diff and less wrapping and the diff is indented the same as the actual code (except it's off-by-one because of the `+`/`-` of diffs).

**Comment by GreenCourt** [comment]
> You mean the sign isn't shown or that the preview isn't working? If there's no preview even  though there is a sign, it's definitely a bug.

Yes, the sign is shown and `:SignifyPreviewHunk` does not show anything.
I found the way to reproduce the bug.

In the repository of vim-signify, please modify the `showcolors.bash` as follows :

```
#!/bin/bash

if ! hash tput 2>/dev/null; then
  fe
    echo "I cannot find the 'tput' program." \
        'You might find it in one of the ncurses packages.' >&2
    exit 1
fi

for i in {0..255}; do

tput sgr0
echo
```

Signs are shown correctly.
Move the cursor to the line of `for i in {0..255}; do` (a sign is shown in at line).
Then `:SignifyPreviewHunk` shows nothing.

My vimrc is :

```
unlet! skip_defaults_vim | ru defaults.vim
set et sts=-1 sw=2
```

And no other plugin is installed.
I confirmed this behavior on two environments.

- macOS Mojave, MacVim 8.1 (Included patches 1-1722), git version 2.20.1 (Apple Git-117)
- Ubuntu 18.04, Vim 8.0 (Included patches: 1-1453), git version 2.17.1

For both environments, vim-signify is the revision https://github.com/mhinz/vim-signify/commit/736466ccce6aaac5e2bd08b3157af1d2e42656a4.

**Comment by mhinz** [comment]
That logic bug should be fixed now!

I also pushed a change that changes the look of the floating window as mentioned above.  It now opens _below_ the current line. And it uses almost the entire width of the window (minus fold/sign/number column). There is no good way to calculate the width of the sign column, but in almost all cases the diff should be aligned with the actual code now.. which is pretty nice!

**Comment by GreenCourt** [comment]
I confirmed the bug is fixed.
Thanks for your fast work!
I am also grad of the aligned preview!

> It now opens below the current line.

I’m worried about the case that multiple lines at the end of the file are deleted.
In the case, only one line can be shown for the previews (of course mouse scroll is available, but very inconvenient).
But I noticed we can adjust the cursor position by `zz` ot `zt`.

**Comment by mhinz** [comment]
Yeah, there seem to be a few edge cases.

In the case you mentioned, I guess it would be most convenient if the plugins just scrolls the window down by 3 or 4 lines. It's not as irritating as scrolling half a window or more and the user doesn't have to find a way to see more of the diff. This way we could guarantee that always at least 3 or 4 lines of diff are shown. In the case of huge diffs you'll have to scroll the window anyway.

And we also have to consider very small windows of less than 3 or 4 in height...

**Comment by kjssad** [comment]
I don't mind the plugin scrolling the window but would it be better to put the popup above the current cursor say when `winheight('%') - winline()` is less than a certain value? We could also limit the popup to a certain number of lines(aside from `winheight('%') - winline()` as max_height)  and make it scrollable. 

The sign column width doesn't matter on nvim so we could move the logic inside vim's `popup_create` function.

**Comment by mhinz** [comment]
I prefer the scrolling variant, because I don't want to hide the cursor. if `winheight('%') - winline()` is smaller than the height of the diff. And to scroll only as many lines as needed up to 6.

Everyone has a different taste, so mine comes first. :-) I plan to add a callback for customization though, although that's only for people who know VimL, of course.

And whereas `:SignifyDiffPreview` is really just meant for a quick diff, `:SignifyDiffPreview!` will use the preview window, in case you want to yank from the diff (or look at a large one).

> The sign column width doesn't matter on nvim

Huh? :) How so?

**Comment by kjssad** [comment]
Yes, the width of the three columns matters on vim but not on neovim. I've tested it with different values for signcolum(e.g. signcolumn=yes:7) and it does ignore the width. I'm on mobile now and can't send screenshots.

**Comment by mhinz** [comment]
You mean it matters but is currently ignored, yup. Unfortunately there's no easy way to get the width of the sign column, so currently we simply assume a width of 2.

Will think about better ways later.

**Comment by GreenCourt** [comment]
> And whereas :SignifyDiffPreview is really just meant for a quick diff, :SignifyDiffPreview! will use the preview window, in case you want to yank from the diff (or look at a large one).

When preview window is used, can it be automatically updated by the keymap `[c`, `]c`, `[C`, `]C` or some autocmd like `CorsorMoved`, `CursorMovedI` or  when signs are updated?
Although we must be careful about performance issue when using autocmd.

When a separate preview window is shown, I think updating is not annoying.

**Comment by mhinz** [comment]
Well, there can be only one preview window and I can't guarantee that another plugin uses the preview window as well, e.g. to display the signature or description of a function under the cursor etc.

Moreover, the feature was never designed to work like that.

I recently refactored the plugin so that the initial function that shells out to get the diff takes a callback function that processes the diff. E.g. on saving we [set signs](https://github.com/mhinz/vim-signify/blob/master/autoload/sy.vim#L75) or in the case of [`:SignifyDiffPreview`](https://github.com/mhinz/vim-signify/blob/master/autoload/sy/repo.vim#L275) we find the correct hunk in the diff and display it in a new window.

So, we get a new diff every time `:SignifyDiffPreview` is executed. One obvious optimization would be to just store the diff from updating the signs in memory and use that instead. But I decided against that because (1) diffs can quickly become huge and VimL isn't the most efficient list processing language out there, (2) because I considered `:SignifyDiffPreview` to be used only occassionally. And it would have an impact for all users of the plugin, even if they don't use `:SignifyDiffPreview` at all.

On the other hand, getting the diff every time is good enough when using git, but not all VCS are that fast. So, storing the diff would be an obvious performance gain for `:SignifyDiffPreview`. So, maybe we should do that anyway.

@jamessan ^ Do you think storing the entire (potentially huge) diff in a VimL list on each update could have a performance impact on older systems?

To continuously preview the current hunk diff, the best way would probably be to use a custom window instead of the preview window. But that means even more code for managing that window etc. By now the feature might be too smart for its own good.

These are my current feelings at least. No final decision yet. :)

**Comment by mhinz** [comment]
`:SignifyDiffPreview` now tries to show as much of the diff as possible and at least 6 lines. For the latter it scrolls if needed.

**Comment by GreenCourt** [comment]
> Moreover, the feature was never designed to work like that.

I understand that.
We already have `:SignifyDIff` to look around multiple hunks.

**Comment by mhinz** [comment]
Attention: `:SignifyDiffPreview` was renamed to `:SignifyHunkPreview`.

This was done because we just introduced another new command for undoing hunks called `:SignifyHunkUndo`.

**Comment by mhinz** [comment]
The command was once again renamed to `:SignifyHunkDiff`. This is the final name.

`:SignifyDiff` (diff everything) and `:SignifyHunkDiff` (diff only the hunk).

**Comment by GreenCourt** [comment]
Thanks for your work!

**Comment by 0xRZ** [comment]
In neovim how do i switch to SignifyHunkDiff floating window?

**Comment by mhinz** [comment]
@0xRZ If you update the plugin, you can now jump to the floating window via `<c-w>w` and friends.
