### ISSUE TITLE
Feature request: improve realtime update

### ISSUE THREAD

**Issue by somospocos** [mhinz/vim-signify#309]
I have g:signify_realtime set to 1, yet I have a situation when an update is not happening, but I would like it to happen. This is my workflow:

1. I change source code files
2. I commit the changes using

    :!fossil commit ...

after this I would like signify to update instantly without me having to decrease the value of updatetime if possible. So far I'm triggering the update by manually saving the file one more time, but I would like to save a few keypresses.

**Comment by mhinz** [comment]
Is this working for you if you put it in your vimrc?

```vim
autocmd ShellCmdPost * call sy#start()
```

**Comment by somospocos** [comment]
Thank you, this works for me with vim 8.1.1486. I'm happy with the workaround, but would like to know if you have any plans to add ShellCmdPost to the list of events that trigger the update if g:signify_realtime is set to 1, so someday it would be possible to get this behavior without having to make the suggested explicit setting to vimrc, or are there any reasons to not do it? Feel free to close the issue when answering this question, even if the answer is negative (I'll just use the approach you suggested then).

**Comment by mhinz** [comment]
Yup, I'll add that tonight. Thanks for testing!

And I'll probably do the same for `VimResume` which should work for a similar use case (that was much more popular in the past): Suspending Vim with `<c-z>`, doing things, resuming with `fg`.

FWIW, we'll soon remove the `g:signify_realtime` option once and for all, making that behaviour the default. You can still disable updates on cursor movements via `autocmd! signify CursorHold,CursorHoldI` afterwards. And even that is only needed at the moment, because some events still require saving the current buffer, but we'll soon make a change so that saving isn't required anymore.

**Comment by mhinz** [comment]
Thanks! ✨
