### ISSUE TITLE
Way to disable vcs plugins?

### ISSUE THREAD

**Issue by kcuzner** [mhinz/vim-signify#319]
I have a situation where I use both `git` and `perforce` in the same folder (yeah...), but I only want signify to operate on the git repository.

I just updated my plugins today and discovered that my previous way of modifying `g:signify_vcs_list` so that only `git` was available no longer works, since `g:signify_vcs_list` doesn't exist anymore (#261). Is there an alternative way to disable individual vcs plugins? Perhaps using `g:signify_vcs_list` was the wrong way to do this in the first place?

Here's my existing vimrc:
```
" signify
" Turn off perforce
let g:signify_vcs_list = ['git']
```

This XKCD seems applicable here: https://xkcd.com/1172/

**Comment by mhinz** [comment]
If you just want to get it done for now, check out the `legacy` branch: https://github.com/mhinz/vim-signify#installation

I know I did quite an aggressive refactoring lately, but there were a few things that I wanted to change for a long time and.. well, it's happening now. I removed a lot of options because a) http://neugierig.org/software/blog/2018/07/options.html and b) they were introduced before Vim was capable of async execution.

`g:signify_vcs_list` was important in pre-async times, because it would delay the Vim start quite a lot when it checked for all installed VCS tools one after the other and blocking during the whole time.

Anyway, I see your issue. But instead of reintroducing `g:signify_vcs_list`, I'd like to introduce a new `g:signify_skip` that takes `{}` and replaces `g:signify_skip_filetype`, `g:signify_skip_filename`, and `g:signify_skip_filename_pattern`.

Maybe something like:

```
let g:signify_skip = {
      \ 'filename': [
      \   '~/projects/foo': ['perforce'],
      \   '~/projects/bar': ['all'],
      \ ],
      \ 'pattern': ['.*supersecret.*'],
      \ 'filetype': {'java': ['all'] },
      \ }
```

This gives us more flexibility than we had before, is easy to extend, and reduces the number of options. Would that work for you?

**Comment by kcuzner** [comment]
I suppose something like skipping a filename pattern would work, but I'd end up turning off perforce altogether for basically `C:\` (yeah it's on windows...). I never use perforce by itself really. I suppose I could also "turn off" perforce by trying to mangle the path or other things so that it can't find the tool, but that is an incredible hack.

I understand that adding options requires real justification and easily leads to software bloat. I use tools on a daily basis plagued by options accumulated over decades and now come with literal 10,000 page manuals. However, for something like this where the "default" installation comes with support for multiple VCS, many of which most people won't use concurrently, it seems like having a way to simply limit the supported VCS borders on basic functionality. All that would be needed would be to add another entry in the `signify_skip` dictionary to skip entire vcs globally. You'd probably already skip patterns and filetypes with `signify_skip`, so skipping vcs as well seems only natural.

**Comment by mhinz** [comment]
Okay, so the commit above should work for your use case.

**Comment by kcuzner** [comment]
I tested and it works for me!

```
" signify
" Turn off perforce
" Undocumented new feature: https://github.com/mhinz/vim-signify/issues/319
let g:signify_skip = {'vcs': { 'deny': ['perforce'] }}
````

**Comment by calid** [comment]
is this still considered undocumented/subject to change?

**Comment by KapJI** [comment]
It actually works fine but missing documentation.

**Comment by polyzen** [comment]
> It actually works fine but missing documentation.

#377
