### ISSUE TITLE
vim-signify is giving errors when I use cfdo over a large number of file in non-git repo

### ISSUE THREAD

**Issue by jdhao** [mhinz/vim-signify#333]
#  summary

I am using `cfdo` command inside Neovim over a lot of files (300), and find that vim-signify is causing me trouble. I am seeing the following two errors:

> Error detected while processing function sy#start[38]..sy#repo#detect[4]..sy#repo#get_diff:

and 

> E903: Process failed to start: too many open files: "/bin/sh"

# Version info

+ Neovim version: NVIM v0.5.0-2b00d1d09
+ Platform: MacOS (maybe not related to Mac)
+ vim-signify: latest master

# Steps to reproduce

+ Install vim-signify to a direcotry, e.g., `/Users/jdhao/.local/share/nvim/plugged/vim-signify`
+ create `init.vim` with the following content:
```
set runtimepath+=/Users/jdhao/.local/share/nvim/plugged/vim-signify
set autowrite
```
+ Create under current directory 300 files using the following script:
```
for i in {0..299}
do
    touch $i.txt && echo "good" > $i.txt
done
```
+ Open nvim with the above config: `nvim -u init.vim`
+ Executing the following command:
    + `:vimgrep /good/gj **/*`
    + `cfdo %s/good/bad/g`

The error should occur once the opened files exceed a certain limit (maybe 56?)

**Comment by kassio** [comment]
I'm getting a similar error when toggling (closing) a NERDTree window:
```
Error detected while processing function sy#util#refresh_windows[9]..sy#start[65]..sy#repo#get_diff:
line   19:
E475: Invalid argument: expected valid directory
```

**Comment by jamessan** [comment]
> I am using `cfdo` command inside Neovim over a lot of files (300), and find that vim-signify is causing me trouble. I am seeing the following two errors:

Makes sense.  Every buffer that `cfdo` visits causes Sy to spawn processes to detect the VCS being used and the diff for that buffer.  Since it happens async, nvim is able to change to the next buffer before that detection is complete, spawning off even more processes.

We have protection against this while a command like `:make`, `:grep`, `:vimgrep`, etc. run because the `QuickFixCmdPre`/`QuickFixCmdPost` events trigger and we block Sy.  However, nothing gives us a heads up about `:cfdo`.

I guess the proper way to guard against this is to have a queue of jobs to process, and only have a certain number outstanding at one time.

**Comment by mhinz** [comment]
We already have [`b:sy.detecting`](https://github.com/mhinz/vim-signify/blob/2542b6459085f3d1e361e8b5bf406dec6448487e/autoload/sy/repo.vim#L9) which gets incremented shortly before a new process is run and decremented when the process finished.

So.. I guess we could also add a `g:sy_detecting` that increments/decrements at the same time as its buffer-local equivalents. And when we hit a threshold of 50 (so when processes start faster than they finish), we just stop because a batch operation was detected. The check would be added [here](https://github.com/mhinz/vim-signify/blob/2542b6459085f3d1e361e8b5bf406dec6448487e/autoload/sy.vim#L8), so that almost no plugin code is run and especially before `b:sy` gets initialized.

When `:cfdo` has finished and the user goes through the buffers, Sy will automatically run on `BufEnter`.

Dirty, but probably works for almost all cases.

Opinions?
