### ISSUE TITLE
The delete sign is not show when a nearby line is changed

### ISSUE THREAD

**Issue by everdimension** [mhinz/vim-signify#350]
Hi!
I have the following problem. Say, initial committed code looks like this:

```
  const obj = {
    a: 1,
    b: 2,
  }
```

If I delete one line, I see the diff with the sign `_1` on the previous line:
```
_1 const obj = {
    b: 2,
  }
```
 But if I also modify next line, I only see the `!` sign on the modified line, and the `_1` sign disappears:
```
  const obj = {
!   b: 3,
  }
```

Is this a bug?

**Comment by calid** [comment]
also experiencing this bug

**Comment by aktau** [comment]
I see a similar bug though in my case an addition after modification is not recognized properly. The diff obtained from `:SignifyDebug`:

```diff
diff --git a/.vimrc b/.vimrc
index bf6dd03..74129af 100644
--- a/.vimrc
+++ b/.vimrc
@@ -106 +106,2 @@ Plug 'rust-lang/rust.vim'
-Plug 'airblade/vim-gitgutter', PlugCond(!PlugActivated('vim-signify'))
+" Plug 'airblade/vim-gitgutter', PlugCond(!PlugActivated('vim-signify'))
+Plug 'mhinz/vim-signify'
@@ -115,0 +117,2 @@ scriptencoding utf-8
+well well well
+
```

The second exclamation mark should be a plus, since it's a pure addition. A screenshot comparison of vim-gitgutter (correct) versus vim-signify (incorrect):

### vim-signify

![Screen Shot 2020-12-03 at 11 20 41](https://user-images.githubusercontent.com/189413/100996706-add96880-3559-11eb-832d-cc48bb0368cf.png)

### vim-gitgutter

![Screen Shot 2020-12-03 at 11 22 54](https://user-images.githubusercontent.com/189413/100996905-f002aa00-3559-11eb-8718-392a90124347.png)
