### ISSUE TITLE
Is it possible to show the symbols in a different column?

### ISSUE THREAD

**Issue by carrascomj** [mhinz/vim-signify#371]
In my config, Coc uses the first and second column on the left (I don't know how they are called), is it possible to show vim-signify signs in the third column (as I had with gitgutter)?

![image](https://user-images.githubusercontent.com/46683255/114034064-250f6800-987e-11eb-9847-dc1d106706cc.png)

As can be seen in the image, the line highlighted in blue was also created but overlaps with Coc, hiding the "created" sign. If it is in the docs, I could not find it.

**Comment by mhinz** [comment]
Vim knows 3 kinds of special columns: 

- sign column (in Vim it always takes 2 columns, in Nvim it's variable)
- number column (taking 3 columns)
- fold column (not used here).

> is it possible to show vim-signify signs in the third column (as I had with gitgutter)?

Where do you mean exactly? Where the relative line numbers are in your screenshot?

The one thing we could easily add, is an option so that the line number is highlighted the same way as the actual sign. So, in your screenshot, the line with the green `+` would also have a green `1`. (Like it's done by CoC in the new two lines.)

As for which sign is shown, it depends on which sign has the higher priority or when they have the same priority, which one was placed last. The default sign priority is 10. You can change this via `:h g:signify_priority`.

(You might also like `:set signcolumn=number`, which shows the first sign in the number column instead.)

**Comment by carrascomj** [comment]
Thank you very much for the detailed explanation! I think it makes sense for me to have it over the CoC/lsp signs and have them color the line numbers like they are doing now (that way I can see both). I had tried changing `g:signify_priority` before but it seems like I was getting the values wrong.

**Comment by mhinz** [comment]
FWIW, I use the following command to list all signs on a line (including priority etc.):

```
command! Signs echo sign_getplaced('.', {'lnum': line('.'), 'group': '*'})
```

Then just `:Signs` on any line with signs.
